/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Vinayak21AcresRouteImport } from './routes/vinayak-21-acres'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as OngoingRouteImport } from './routes/ongoing'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as HoablTheSarayuRouteImport } from './routes/hoabl-the-sarayu'
import { Route as GodrejBlueRouteImport } from './routes/godrej-blue'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompletedRouteImport } from './routes/completed'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const Vinayak21AcresRoute = Vinayak21AcresRouteImport.update({
  id: '/vinayak-21-acres',
  path: '/vinayak-21-acres',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const OngoingRoute = OngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const HoablTheSarayuRoute = HoablTheSarayuRouteImport.update({
  id: '/hoabl-the-sarayu',
  path: '/hoabl-the-sarayu',
  getParentRoute: () => rootRouteImport,
} as any)
const GodrejBlueRoute = GodrejBlueRouteImport.update({
  id: '/godrej-blue',
  path: '/godrej-blue',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompletedRoute = CompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/completed': typeof CompletedRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/godrej-blue': typeof GodrejBlueRoute
  '/hoabl-the-sarayu': typeof HoablTheSarayuRoute
  '/locations': typeof LocationsRoute
  '/ongoing': typeof OngoingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/vinayak-21-acres': typeof Vinayak21AcresRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/completed': typeof CompletedRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/godrej-blue': typeof GodrejBlueRoute
  '/hoabl-the-sarayu': typeof HoablTheSarayuRoute
  '/locations': typeof LocationsRoute
  '/ongoing': typeof OngoingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/vinayak-21-acres': typeof Vinayak21AcresRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/completed': typeof CompletedRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/godrej-blue': typeof GodrejBlueRoute
  '/hoabl-the-sarayu': typeof HoablTheSarayuRoute
  '/locations': typeof LocationsRoute
  '/ongoing': typeof OngoingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/vinayak-21-acres': typeof Vinayak21AcresRoute
  '/projects/$slug': typeof ProjectsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/completed'
    | '/contact'
    | '/gallery'
    | '/godrej-blue'
    | '/hoabl-the-sarayu'
    | '/locations'
    | '/ongoing'
    | '/projects'
    | '/vinayak-21-acres'
    | '/projects/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/completed'
    | '/contact'
    | '/gallery'
    | '/godrej-blue'
    | '/hoabl-the-sarayu'
    | '/locations'
    | '/ongoing'
    | '/projects'
    | '/vinayak-21-acres'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/completed'
    | '/contact'
    | '/gallery'
    | '/godrej-blue'
    | '/hoabl-the-sarayu'
    | '/locations'
    | '/ongoing'
    | '/projects'
    | '/vinayak-21-acres'
    | '/projects/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CompletedRoute: typeof CompletedRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GodrejBlueRoute: typeof GodrejBlueRoute
  HoablTheSarayuRoute: typeof HoablTheSarayuRoute
  LocationsRoute: typeof LocationsRoute
  OngoingRoute: typeof OngoingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  Vinayak21AcresRoute: typeof Vinayak21AcresRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vinayak-21-acres': {
      id: '/vinayak-21-acres'
      path: '/vinayak-21-acres'
      fullPath: '/vinayak-21-acres'
      preLoaderRoute: typeof Vinayak21AcresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ongoing': {
      id: '/ongoing'
      path: '/ongoing'
      fullPath: '/ongoing'
      preLoaderRoute: typeof OngoingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hoabl-the-sarayu': {
      id: '/hoabl-the-sarayu'
      path: '/hoabl-the-sarayu'
      fullPath: '/hoabl-the-sarayu'
      preLoaderRoute: typeof HoablTheSarayuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godrej-blue': {
      id: '/godrej-blue'
      path: '/godrej-blue'
      fullPath: '/godrej-blue'
      preLoaderRoute: typeof GodrejBlueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/completed': {
      id: '/completed'
      path: '/completed'
      fullPath: '/completed'
      preLoaderRoute: typeof CompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CompletedRoute: CompletedRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GodrejBlueRoute: GodrejBlueRoute,
  HoablTheSarayuRoute: HoablTheSarayuRoute,
  LocationsRoute: LocationsRoute,
  OngoingRoute: OngoingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  Vinayak21AcresRoute: Vinayak21AcresRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
